[package]
name = "aw-models"
version = "0.1.0"
authors = ["Johan Bj√§reholt <johan@bjareho.lt>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aw_models"
crate-type = ["lib", "cdylib"]
path = "src/lib.rs"


[dependencies]
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = { version = "0.8", features = ["chrono"] }
