[package]
name = "aw-client-rust"
version = "0.1.0"
edition = "2018"
authors = ["Johan BjÃ¤reholt <johan@bjareho.lt>"]

[dependencies]
reqwest = { version = "0.10", features = ["json", "blocking"] }
gethostname = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
aw-models = { path = "../aw-models" }

[dev-dependencies]
aw-datastore = { path = "../aw-datastore" }
aw-server = { path = "../aw-server", default-features = false, features=[] }
